### ISSUE TITLE
Fails to migrate RDS MYSQL -> Supabse

### ISSUE THREAD

**Issue by georgelewi5** [mansueli/Supa-Migrate#7]
Colab takes 0 seconds to run and transfers no data.

**Comment by tomowen02** [comment]
@mansueli 

Errors/ fixes in the first code block:

When executing:
!unzip v3.6.9.zip -d pgloader -A
Output: filename not matched -A
Should be:
!unzip -a v3.6.9.zip -d pgloader

Now in the wrong directory for:
!./build/bin/pgloader --help
Should be:
!./build/bin/pgloader --help

Errors/ fixes during the final code block:
--before and --after options should be before source and target

There should also really be an option to change the Supabase port because the default that is hardcoded does not match my database.

If you have a ! in the password to the RDS database, it will cause an error. This is because ! is a special character. Wrapping mysql://$USER:$PASSWORD@$HOST:$PORT/$SOURCE_DB in single quotations

**Comment by mansueli** [comment]
Hey @tomowen02, thanks. 

I've pushed a commit fixing the build and it worked on my test. If it still failing and you can fix, feel free to send a PR.

**Comment by mansueli** [comment]
I've tested this with Supavisor (session mode) & made a successful MySQL 2 Postgres migration with this new [version](https://github.com/mansueli/Supa-Migrate/commit/9f3f901fcf05e40c51976d0244a96c9be8a97602):

https://github.com/mansueli/Supa-Migrate/blob/main/Amazon_RDS_to_Supabase.ipynb
